spring:
  application:
    name: config-server
  profiles:
    active: native
  
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Anguswin/sp_repo
#          searchPaths: sp-config
#          #username: your-username
#          #password: your-password
          
  rabbitmq:
    host: 172.16.52.132
    port: 5672
    username: admin
    password: admin
  
    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
